### ISSUE TITLE
Run DPO step with multibinarized dataset

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/notus#12]
One important open question, especially for distilabel is: does generating more pairs of chosen/rejected samples improve the DPO process. Both Notus, Zephyr and Tulu, just use the best chosen and a random rejected.

We need to run an experiment to better understand how multibinarization impacts the model.

The dataset is ready:
https://huggingface.co/datasets/argilla/notus-uf-dpo-multibinarized

It contains pairs with the best chosen response and then several pairs with responses that go a lower rating, so instead of generating just one sample per UF row (choosing a random rejected), we generated >=1<4 pairs

**Comment by alvarobartt** [comment]
Yes, I think it's going to be an insightful experiment! I've created a milestone for it https://github.com/argilla-io/notus/milestone/2 (note it's v1.2 as I was planning to re-run everything for v1.1 using the dataset curated in combination with AllenAI at https://huggingface.co/datasets/allenai/ultrafeedback_binarized_cleaned, see its milestone at https://github.com/argilla-io/notus/milestone/1)

**Comment by alvarobartt** [comment]
Experiments already ran and fine-tuned model uploaded to [`argilla/notus-7b-v1.1`](https://huggingface.co/argilla/notus-7b-v1.1) fine-tuned using DPO on top of [`alignment-handbook/zephyr-7b-sft-full`](https://huggingface.co/alignment-handbook/zephyr-7b-sft-full) using [`argilla/ultrafeedback-multi-binarized-quality-preferences-cleaned`](https://huggingface.co/datasets/argilla/ultrafeedback-multi-binarized-quality-preferences-cleaned).

See the Weights and Biases logs at https://wandb.ai/argilla-io/notus-7b-v1.1/runs/k3z5agr5?workspace=user-alvarobartt

A potential follow up experiment would be doing a proper train/test split, as with the current approach we may have introduced some of the prompt-chosen pairs into the evaluation set, which shouldn't have affected the training itself, but probably worth at least updating the dataset at [`argilla/ultrafeedback-multi-binarized-quality-preferences-cleaned`](https://huggingface.co/datasets/argilla/ultrafeedback-multi-binarized-quality-preferences-cleaned) with a proper train/test split plus adding the dataset card.
